version: '3'

services:
  backend:
    container_name: 'kupipodariday-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  postgres:
    container_name: 'kupipodariday-database'
    image: postgres:12.12-alpine
    restart: on-failure
    env_file: .env

  frontend:
    container_name: 'kupipodariday-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    restart:
      on-failure
    ports:
      - '8081:80'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 